export const enum SlotsType {
  // 文本节点或Fragment
  TEXT_OR_FRAGMENT_CONTENT = 'TEXT_OR_FRAGMENT_CONTENT',
  // 元素节点
  ELEMENT_CONTENT = 'ELEMENT_CONTENT',
  // 空节点
  FRAGMENT_CONTENT = 'FRAGMENT_CONTENT',
  COMPONENT_CONTENT = "COMPONENT_CONTENT"
}
